openapi: 3.0.1
info:
  title: SmartCert API (with Download Link)
  version: 1.0.0
servers:
  - url: https://smart-cert-manager.onrender.com
paths:
  /renew:
    post:
      summary: Renew a certificate
      operationId: renewCertificate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - host
              properties:
                host:
                  type: string
                mock:
                  type: boolean
                  default: true
      responses:
        '200':
          description: Renewal confirmation
          content:
            application/json:
              schema:
                type: object
                properties:
                  domain:
                    type: string
                  success:
                    type: boolean
                  output:
                    type: string
                  mode:
                    type: string
  /log:
    get:
      summary: Get renewal log
      operationId: getRenewalLog
      responses:
        '200':
          description: Renewal log in JSON
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  log:
                    type: object
                    additionalProperties:
                      type: string
  /export/pdf-link:
    get:
      summary: Get link to download PDF report
      operationId: getPdfReportLink
      responses:
        '200':
          description: Link to the downloadable PDF file
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  download_link:
                    type: string
