openapi: 3.0.1
info:
  title: SmartCert API
  version: 1.0.0
  description: Full SmartCert API for renewal, log, and PDF export
servers:
  - url: https://smart-cert-manager.onrender.com
paths:
  /renew:
    post:
      summary: Renew a certificate
      operationId: renewCertificate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - host
              properties:
                host:
                  type: string
                mock:
                  type: boolean
                  default: true
      responses:
        '200':
          description: Mock renewal response
          content:
            application/json:
              schema:
                type: object
                properties:
                  domain:
                    type: string
                  success:
                    type: boolean
                  output:
                    type: string
                  mode:
                    type: string
  /log:
    get:
      summary: Get renewal log
      operationId: getRenewalLog
      responses:
        '200':
          description: Renewal log in JSON format
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  log:
                    type: object
                    additionalProperties:
                      type: string
  /export/pdf:
    get:
      summary: Download certificate PDF report
      operationId: getPdfReport
      responses:
        '200':
          description: Certificate report in PDF format
          content:
            application/pdf:
              schema:
                type: string
                format: binary
